version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install

  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run tests with Maven
          command: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test