name: Javadoc and GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Updated to match your pom.xml
          distribution: 'temurin'  # Corrected distribution

      - name: Build project and generate Javadoc
        run: mvn clean install javadoc:javadoc

      - name: Deploy Javadoc to GitHub Pages
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git clone --branch gh-pages https://github.com/username/repository.git gh-pages || git clone --single-branch --branch main https://github.com/username/repository.git gh-pages
          cp -r target/site/apidocs/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Update Javadoc"
          git push origin gh-pages
