name: Javadoc and GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Updated to match your pom.xml
          distribution: 'temurin'  # Corrected distribution

      - name: Build project and generate Javadoc
        run: mvn clean install javadoc:javadoc

      - name: Deploy Javadoc to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "raniaChouchene"
          git config --global user.email "rania.chouchene.2019@gmail.com"
          git clone --branch circleci-project-setup https://github.com/raniaChouchene/ceri-m1-techniques-de-test.git circleci-project-setup || git clone --single-branch --branch main https://github.com/raniaChouchene/ceri-m1-techniques-de-test.git circleci-project-setup
          cp -r target/site/apidocs/* circleci-project-setup/
          cd circleci-project-setup
          git add .
          git commit -m "Update Javadoc"
          git push origin circleci-project-setup
